version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 3000

workflows:
  version: 2
  workflow:
    jobs:
      - build
