version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    parallelism: 31
    resource_class: small
    steps:
      - run: echo "hello"

workflows:
  version: 2
  app:
    jobs:
      - build
