version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $DEPLOY_KEY
  cron-job:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo $DEPLOY_KEY

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: development
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - test/scheduled-workflow
    jobs:
      - cron-job
