version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:latest
      - image: nginx:latest
      - image: circleci/postgres:9.6-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: pytestSamplePassword12345
    steps:
      - run: sleep 3000

workflows:
  version: 2
  workflow:
    jobs:
      - build
