version: 2

jobs:
  setup:
    docker:
      - image: circleci/node:latest
    working_directory: /dev/shm
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
