version: 2

jobs:
  setup:
    docker: 
      - image: alpine
    steps:
      - run: 
          name: Test
          command: echo $HELLO 
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup:
          context: test2
