version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-app-{{ checksum "yarn.lock" }}
        - v1-app-
    - run: yarn install
    - save_cache:
        paths:
          - node_modules
        key: v1-app-{{ checksum "yarn.lock" }}
    - run:
        name: Run tests with JUnit as reporter
        command: yarn run test
    - codecov/upload:
        file: reports/coverage/clover.xml
    - store_test_results:
        path: reports
    - store_artifacts:
        path: reports

workflows:
  version: 2
  test:
    jobs:
      - test