version: 2

jobs:
  setup:
    docker: 
      - image: alpine
    steps:
      - run: 
          name: Test
          command: echo $CIRCLE_BUILD_NUM 
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/

