version: 2

references:
  envvars-test: &envvars-test
    KEY: test
  job: &job
    docker:
      - image: alpine
    resource_class: xlarge
    environment: *envvars-test
    steps:
      - run: env

jobs:
  test1:
    docker:
      - image: alpine
    resource_class: xlarge
    environment: *envvars-test
    steps:
      - checkout
      - run:
          name: "checkout submodules"
          command: |
            echo "hello"
  
  test2:
    <<: *job
    environment: *envvars-test
  test3:
    <<: *job
    environment: *envvars-test
  test4:
    <<: *job
    environment: *envvars-test
  test5:
    <<: *job
    environment: *envvars-test
  test6:
    <<: *job
    environment: *envvars-test
  test7:
    <<: *job
    environment: *envvars-test
  test8:
    <<: *job
    environment: *envvars-test
  test9:
    <<: *job
    environment: *envvars-test
  test10:
    <<: *job
    environment: *envvars-test
  test11:
    <<: *job
    environment: *envvars-test
  test12:
    <<: *job
    environment: *envvars-test
  test13:
    <<: *job
    environment: *envvars-test
  test14:
    <<: *job
    environment: *envvars-test
  test15:
    <<: *job
    environment: *envvars-test
  test16:
    <<: *job
    environment: *envvars-test
  test17:
    <<: *job
    environment: *envvars-test
  test18:
    <<: *job
    environment: *envvars-test
  test19:
    <<: *job
    environment: *envvars-test
  test20:
    <<: *job
    environment: *envvars-test
  test21:
    <<: *job
    environment: *envvars-test
  test22:
    <<: *job
    environment: *envvars-test
  test23:
    <<: *job
    environment: *envvars-test
  test24:
    <<: *job
    environment: *envvars-test
  test25:
    <<: *job
    environment: *envvars-test
  test26:
    <<: *job
    environment: *envvars-test

workflows:
  version: 2
  test:
    jobs:
      - test1