version: 2
jobs:
  build:
    machine:
      image: registry.hub.docker.com/circleci/node:latest
    steps:
      - checkout
      - run:
          name: build Elixir image
          command: docker build -t circleci/elixir:example .
  build-no-dlc-default:
    machine: true
    resource_class: default
    steps:
      - checkout
      - run:
          name: build Elixir image
          command: docker build -t circleci/elixir:example .
  build-no-dlc-medium:
    machine: true
    steps:
      - checkout
      - run:
          name: build Elixir image
          command: docker build -t circleci/elixir:example .
  # build-no-dlc-large:
  #   machine: true
  #   resource_class: large
  #   steps:
  #     - checkout
  #     - run:
  #         name: build Elixir image
  #         command: docker build -t circleci/elixir:example .
  #
  build-dlc-with-setup_remote_docker:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  # default - false
      - run:
          name: build Elixir image
          command: docker build -t circleci/elixir:example .
  build-dlc-with-setup_remote_docker-medium:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  # default - false
      - run:
          name: build Elixir image
          command: docker build -t circleci/elixir:example .

workflows:
  version: 2
  app:
    jobs:
      - build
      # - build-no-dlc-medium
      # # - build-no-dlc-large
      # # - build-no-dlc-default
      # - build-dlc-with-setup_remote_docker
      # - build-dlc-with-setup_remote_docker-medium
