version: 2
jobs:
  build-setup_remote_docker:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build Elixir image
          command: docker build -t circleci/elixir:example .
  build-setup_remote_docker-v18:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: build Elixir image
          command: docker build -t circleci/elixir:example .
  build-dlc-with-setup_remote_docker-v19:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: build Elixir image
          command: docker build -t circleci/elixir:example .

workflows:
  version: 2
  app:
    jobs:
      - build-setup_remote_docker
      - build-setup_remote_docker-v18
      - build-setup_remote_docker-v19
