version: 2
jobs:
  build:
    machine:
      machine:
      image: ubuntu-1604:201903-01    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3,
    steps:
      - checkout
      - run: echo "hello"

workflows:
  version: 2
  app:
    jobs:
      - build
