version: 2

jobs:
  setup:
    docker: 
      - image: alpine
    steps:
      - checkout
      - run:
          command: |
            pkill -ABRT -f circleci-agent

  
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
